### ISSUE TITLE
Hide Password while using the installer or chpasswd

### ISSUE THREAD

**Issue by Toby4213** [swizzin/swizzin#380] opened 2020-08-07 09:55 UTC
## Bug description
Setting the master password displays it in cleartext

## Reproduction steps
Running the installer script prompts for the password which is displayed in cleartext
or running `box chpasswd user` and typing the password

## Installed applications through swizzin
Doesn't matter, box itself.

## Expected behavior
The password should not be displayed in cleartext. Instead it should be *'ed out in case of the setup script and display nothing at all using the chpasswd command, just like the normal passwd.

## Server Info
 - OS: Debian 10
 - Image Source: Quckstart from this repo

## Is Swizzin up to date?
yes, commit hash ca2a688

## Additional context
Also I hope that the password isn't stored anywhere in cleartext...

**Comment by flying-sausages** [comment] 2020-09-19 13:31
I've changed a lot of these in my `echo` PR, still need to figure out how to in the whiptails.

Otherwise a dupe of #123

**Closed** 2021-01-27 01:54 UTC
