### ISSUE TITLE
[BUG] qBittorrent 4.6.4 fails build

### ISSUE THREAD

**Issue by un2t** [swizzin/swizzin#1147] opened 2024-03-25 10:40 UTC
### What happened?

Steps to reproduce:

1. sudo box upgrade qbittorrent
2. Choose 4.6.4 from the version list
3. Error 'The cmake build of qbittorrent did not complete successfully'

Expected results: Apt install complete

### Swizzin commit

6ac45d1

### What OS are you using?

Debian 12 (bookworm)

### What architecture is your OS?

amd64

### Relevant logs and output

```plaintext
CMake Error in src/base/CMakeLists.txt:

  Imported target "Qt::CorePrivate" includes non-existent path

    "/usr/include/x86_64-linux-gnu/qt6/QtCore/6.4.2"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.
```

**Comment by AncientVamp** [comment] 2024-03-25 22:24
Yep. getting the same error.

**Comment by insertfahim** [comment] 2024-03-27 05:31
getting the same error on **Debian 12**

**Comment by wii747** [comment] 2024-03-29 23:53
Debian 12 same error 

CMake Error in src/base/CMakeLists.txt:
  Imported target "Qt::CorePrivate" includes non-existent path

    "/usr/include/x86_64-linux-gnu/qt6/QtCore/6.4.2"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.



CMake Error in src/base/CMakeLists.txt:
  Imported target "Qt::CorePrivate" includes non-existent path

    "/usr/include/x86_64-linux-gnu/qt6/QtCore/6.4.2"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.



-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    CMAKE_C_FLAGS


CMake Generate step failed.  Build files cannot be regenerated correctly.

**Comment by liaralabs** [comment] 2024-03-30 00:52
It is due this is appear to a dependency bump, which is a bit ridiculous considering this was a patch release:

> OTHER: Minimum supported versions: Qt: 6.5, Boost: 1.76, OpenSSL: 3.0.2

**Comment by liaralabs** [comment] 2024-03-30 01:54
This will be a bigger undertaking than expected. Unfortunately, bullseye/focal are going to lose updates moving forward. That said, a fair bit of work needs to be done to support 4.6.4 as of yet.

If you really need to build the 4.6 branch now, just export the variable below before installing. 4.6.4 isn't supported yet
```
export QBITTORRENT_VERSION=4.6.3
```

**Comment by liaralabs** [comment] 2024-04-07 14:44
To follow up on this, it looks to be a potentially missing dependency. Debian faced the same packaging issue:

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1067667

The problem is resolved with `qt6-base-private-dev`

I'm currently afk, so if anyone is eager to test recompiling after installing this dependency, please let me know how it goes.

**Comment by un2t** [comment] 2024-04-07 14:58
hey liara

thanks for looking at this, deploying the dependency seem to resolve the compile issue for qbittorrent 4.6.4

when you are back behind the keyboard, would you please be so kind as to update the dependencies  in swizzin to include qt6-base-private-dev ? 

appreciate it!

**Comment by liaralabs** [comment] 2024-04-07 15:00
Thanks for the quick confirmation. I'll get a quick fix queued up for everyone when I have time (may be later today)

**Comment by liaralabs** [comment] 2024-05-11 22:06
This was fixed in https://github.com/swizzin/swizzin/commit/953e4c716a0e466e4e511ee15832477d747ff28a

**Closed by liaralabs** 2024-05-11 22:06 UTC
Labels: bug
