### ISSUE TITLE
Cannot login into the new panel

### ISSUE THREAD

**Issue by Sockolet** [swizzin/swizzin#348] opened 2020-06-02 13:31 UTC
# Please note that issues that do not follow the format to some degree can be automatically closed.

## Bug description
After have updated Swizzin to the latest master branch, I cannot login directly to the new panel.

## Reproduction steps
1. Visit root site to access the panel: https://mydomain.com
2. Type your credentials and click on 'Login'
3. Nothing happens. You get stuck in the Login site no matter how many times you click on the 'Login' button.

## Installed applications through swizzin
Nginx, panel

## Expected behavior
Being able to log into my panel.

## Server Info
 - OS: Ubuntu 18.04
 - Image Source: vanilla download from Ubuntu website
 - Fails either accesing by Chrome or Firefox.

## Is Swizzin up to date?
Yes it is. Indeed it started to happen after have updated.

- Please mention the commit hash you are seeing
HEAD is now at 65f8719

## Additional context
If I visit one of the applications that I have installed, Sonarr for example, by visiting https://mydomain.com/sonarr, it asks me for my credentials in the legacy way (a pop-up a box). There I can access without issues and if then I try to access the panel, I can do it without need to pass through the Login site.

Please let me know if you need any log or something.
Thank you very much in advance.

**Comment by liaralabs** [comment] 2020-06-02 17:47
Are you running the most recent commit of the panel? There were a few fixes that went in and I reverted a few lines of code at one point; however, I have done extensive testing on this before I pushed this, so I'm a bit confused by this.

If you have the latest commit (as of your issue, 0c374390170f92fef92199b32f34cc03541d6a55), can you try reverting this commit (in `/opt/swizzin/swizzin`) -- it may have removed some code I figured was not doing anything

**Comment by Sockolet** [comment] 2020-06-03 07:52
Sorry but I'm going to need you educate me abot how to do that :)

The way that I used to upgrade Swizzin was 'box update'.
If I go to /opt/swizzin/swizzin, I don't see where I can set or revert that commit that you mention:

meiden@j3455:/opt/swizzin/swizzin$ ls
core         __pycache__  requirements.txt  static       swizzin.py  wsgi.py
gunicorn.sh  README.md    setup.sh          swizzin.cfg  templates

Thank you!

**Comment by liaralabs** [comment] 2020-06-04 20:39
In the `/opt/swizzin/swizzin` dir:

```
git show
```

Will show you the current commit info.
In that same directory
```
git revert 0c374390170f92fef92199b32f34cc03541d6a55
```
Will revert the commit in question. A dialog box asking for commit details will be created, you can simply close it. A message may popup complaining about your git config username, etc. You can ignore this since you aren't pushing this back to the repo.

```
git show
```

Should show the commit in question is now reverted

and

```
systemctl restart panel
```

Will restart the panel for you to test against

**Comment by Sockolet** [comment] 2020-06-05 14:00
Thank you very much for the explanation.
Funny things:

`meiden@j3455:/opt/swizzin/swizzin$ sudo git show
commit 0c374390170f92fef92199b32f34cc03541d6a55 (HEAD -> master, origin/master, origin/HEAD)
Author: liaralabs <liara@swizzin.ltd>
Date:   Sun May 31 18:44:27 2020 -0700

    Comment out unnecessary code for now

diff --git a/swizzin.py b/swizzin.py
index d257a6b..3bee5b2 100755
--- a/swizzin.py
+++ b/swizzin.py
@@ -95,15 +95,15 @@ def reload_htpasswd():
     if flask.request.endpoint == 'index':
         htpasswd.load_users(app)
 
-@app.after_request
-def apply_headers(response):
-    if flask.request.referrer == "{}login".format(flask.request.host_url):
-        response.headers["WWW-Authenticate"] = 'basic realm="{0}"'.format(current_app.config['FLASK_AUTH_REALM'])
-    if flask.request.referrer == "{}login/auth".format(flask.request.host_url):
-        response.headers["WWW-Authenticate"] = 'basic realm="{0}"'.format(current_app.config['FLASK_AUTH_REALM'])
-    if flask.request.referrer == "{}logout".format(flask.request.host_url):
-        response.headers["WWW-Authenticate"] = 'basic realm="{0}"'.format(current_app.config['FLASK_AUTH_REALM'])
-    return response
+#@app.after_request
+#def apply_headers(response):
+#    if flask.request.referrer == "{}login".format(flask.request.host_url):
+#        response.headers["WWW-Authenticate"] = 'basic realm="{0}"'.format(current_app.config['FLASK_AUTH_REALM'])
+#    if flask.request.referrer == "{}login/auth".format(flask.request.host_url):
commit 0c374390170f92fef92199b32f34cc03541d6a55 (HEAD -> master, origin/master, origin/HEAD)
Author: liaralabs <liara@swizzin.ltd>
Date:   Sun May 31 18:44:27 2020 -0700

    Comment out unnecessary code for now

diff --git a/swizzin.py b/swizzin.py
index d257a6b..3bee5b2 100755
--- a/swizzin.py
+++ b/swizzin.py
@@ -95,15 +95,15 @@ def reload_htpasswd():
     if flask.request.endpoint == 'index':
         htpasswd.load_users(app)
 
-@app.after_request
-def apply_headers(response):
-    if flask.request.referrer == "{}login".format(flask.request.host_url):
-        response.headers["WWW-Authenticate"] = 'basic realm="{0}"'.format(current_app.config['FLASK_AUTH_REALM'])
-    if flask.request.referrer == "{}login/auth".format(flask.request.host_url):
-        response.headers["WWW-Authenticate"] = 'basic realm="{0}"'.format(current_app.config['FLASK_AUTH_REALM'])
-    if flask.request.referrer == "{}logout".format(flask.request.host_url):
-        response.headers["WWW-Authenticate"] = 'basic realm="{0}"'.format(current_app.config['FLASK_AUTH_REALM'])
-    return response
+#@app.after_request
+#def apply_headers(response):
+#    if flask.request.referrer == "{}login".format(flask.request.host_url):
+#        response.headers["WWW-Authenticate"] = 'basic realm="{0}"'.format(current_app.config['FLASK_AUTH_REALM'])
+#    if flask.request.referrer == "{}login/auth".format(flask.request.host_url):
+#        response.headers["WWW-Authenticate"] = 'basic realm="{0}"'.format(current_app.config['FLASK_AUTH_REALM'])
+#    if flask.request.referrer == "{}logout".format(flask.request.host_url):
+#        response.headers["WWW-Authenticate"] = 'basic realm="{0}"'.format(current_app.config['FLASK_AUTH_REALM'])
+#    return response
 
 @app.errorhandler(401)
 def unauthorized(e):
`

`meiden@j3455:/opt/swizzin/swizzin$ sudo git revert 0c374390170f92fef92199b32f34cc03541d6a55
error: your local changes would be overwritten by revert.
hint: commit your changes or stash them to proceed.
fatal: revert failed`

**Comment by LaMpiR** [comment] 2020-06-25 15:21
On Win10 Pro x64 Chrome is doing just fine, but on Brave browser I am getting the same problem.

**Comment by liaralabs** [comment] 2020-06-25 17:19
Sorry for lapsing on this -- moving has taken up a very large portion of my time.

@Sockolet it looks like your git revert failed due to local changes -- did you make any modifications to `swizzin.py` that might cause a conflict? You may need to run `box update` to reset your repo to the default state.

@LaMpiR I'm unable to reproduce this issue on any browser at all :confused: Brave, Chrome, Chromium and FF are all working without issue on my end.

Are your browsers up to date?

**Comment by LaMpiR** [comment] 2020-06-25 17:27
Bravo: Version 1.10.97 Chromium: 83.0.4103.116 (Official Build) (64-bit) - The latest one.

Attached a zip video file from Bravo.

[2020-06-25_19-25-32.zip](https://github.com/liaralabs/swizzin/files/4832895/2020-06-25_19-25-32.zip)

**Comment by liaralabs** [comment] 2020-06-25 17:28
Do you have javascript disabled? The login form requires JS.

**Comment by LaMpiR** [comment] 2020-06-25 17:32
Javascript setting is: Allow (default).
Brave Shield is Down.
![web_settings](https://user-images.githubusercontent.com/851778/85769781-9aa8ae00-b71a-11ea-992d-c5fcd140f53d.png)

**Comment by liaralabs** [comment] 2020-06-25 17:36
Is there any information in the developer console when you load the page or click login? (F12)

Otherwise, if you fill the login form and send the command `login()` from the dev console, does anything happen?

Finally, it looks like you are clicking login -- does hitting enter work?

**Comment by LaMpiR** [comment] 2020-06-25 18:06
I tried with enter as well, the same.

Click:
`httpauth.js:34 GET https://username:password@serverurl.com/ net::ERR_TUNNEL_CONNECTION_FAILED
login @ httpauth.js:34
onclick @ login:67
httpauth.js:34 Uncaught DOMException: Failed to execute 'send' on 'XMLHttpRequest': Failed to load 'https://username:password@serverurl.com/'.
    at login (https://serverurl.com/static/js/httpauth.js:34:6)
    at HTMLInputElement.onclick (https://serverurl.com/login:67:118)`

Enter:
`httpauth.js:34 GET https://username:password@serverurl.com/ net::ERR_TUNNEL_CONNECTION_FAILED
login @ httpauth.js:34
enter @ httpauth.js:45
httpauth.js:34 Uncaught DOMException: Failed to execute 'send' on 'XMLHttpRequest': Failed to load 'https://username:password@serverurl.com/'.
    at login (https://serverurl.com/static/js/httpauth.js:34:6)
    at HTMLDocument.enter (https://serverurl.com/static/js/httpauth.js:45:22)
login @ httpauth.js:34
enter @ httpauth.js:45`

**Comment by liaralabs** [comment] 2020-06-25 18:18
Ok, let's try this. Can you populate the username/password field as before and then try running the following commands from dev console? Should be able to just paste this straight in:

```
var username = document.getElementById("basic-username").value;
var password = document.getElementById("basic-password").value;
$.ajax
({
  type: "GET",
  url: "/",
  username: username,
  password: password,
  async: true,
  success: function (){
    document.location = '/';
  }
});
```

**Comment by LaMpiR** [comment] 2020-06-25 18:25
My VPN was on and it didn't work. I got this error:
(Version 1 of the code)
`{readyState: 1, getResponseHeader: ƒ, getAllResponseHeaders: ƒ, setRequestHeader: ƒ, overrideMimeType: ƒ, …}
jquery.min.js:2 GET https://username:pass@serverurl.com/ net::ERR_TUNNEL_CONNECTION_FAILED`

Using the same code without vpn worked.

Using the second version of the code with VPN got me a incorrect password popup.
Using the second version of the code without VPN worked.

**Comment by liaralabs** [comment] 2020-06-25 19:09
What sort of VPN are you using? On my end with Wireguard on or off, it makes no difference here.

It seems the VPN is somehow interfering with the sending of credentials in your URLs (hence why on the second possible code snippet you receive a basic authentication pop-up).

Without knowing more about the VPN solution, the only possible work around may be adding an option to disable forms login entirely for folks who would prefer to use the old style.

**Comment by LaMpiR** [comment] 2020-06-25 19:13
I am using a NordVPN browser extension and it worked very well before. Maybe the update will sort it out. 

Are there any advantages to the new login style?

I used the old with as an url user:pass@serverurl.com to login instantly :)

**Comment by liaralabs** [comment] 2020-06-25 19:15
The advantage is mostly just looks; however, it is admittedly hacked together to workaround various limitations of basic auth.

With the new style you should still be able to use:

```
user:pass@serverurl.com/login/auth
```

As a bookmarklet which should redirect you to home once logged in.

Do you receive errors if you use NordVPN at a system level rather than a browser level?

**Comment by LaMpiR** [comment] 2020-06-25 19:52
System level works fine, browser level makes a problem.

Using an url with /login/auth gives me this panel both in Brave and in Chrome.
![swiz](https://user-images.githubusercontent.com/851778/85788981-18c28000-b72e-11ea-8634-afc1e46fb01d.PNG)

**Comment by Sockolet** [comment] 2020-06-25 19:57
Hi there,

Mu issue isnt related to the one reported by lampir at all.
If I click on the login button, it refresh the page and clears the username and password boxes.
And it happens to me in Windows, Linux and Android. No matter which browser. So it is in server side 100%.

**Comment by liaralabs** [comment] 2020-06-25 20:00
@Sockolet Can you please try the troubleshooting steps outline in previous replies? Even if you have different behavior it may help uncover some further info:

https://github.com/liaralabs/swizzin/issues/348#issuecomment-649721966

**Comment by Sockolet** [comment] 2020-06-25 20:11
> @Sockolet Can you please try the troubleshooting steps outline in previous replies? Even if you have different behavior it may help uncover some further info:
> 
> [#348 (comment)](https://github.com/liaralabs/swizzin/issues/348#issuecomment-649721966)

I don't know if this is something:

VM276 httpauth.js:33 [Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
login @ VM276 httpauth.js:33
onclick @ login:67
Navigated to https://***********.duckdns.org/login (*'s are mine)

If I send login(), exactly same message.

Thank you very much for your help.

**Comment by Sockolet** [comment] 2020-06-27 09:03
Hi @liaralabs , does that error give you any clue about what can be happening?

**Comment by liaralabs** [comment] 2020-06-30 20:28
Unfortunately the error doesn't really provide me with any further insight.

We've now had a second report of a browser extension directly causing the issue -- do you have any extensions that may be on that you can try disabling?

**Comment by liaralabs** [comment] 2020-07-28 21:03
Please note that for those who are having issues with the new Forms based login that a new option has been added to the panel and you configure it to disable the forms login and go back to fully "basic" auth.

Just add
```
FORMS_LOGIN = False
```
to swizzin.cfg

Regretfully, changing the JS does not seem to make a difference on the ability of a browser to login and most of these login issues appear to be driven by a plugin or extension in the browser. There is not much else at this point that can be changed to make the browser accept the credentials over XMLHTTP requests without the presence of a basic auth dialog.

**Comment by Sockolet** [comment] 2020-08-16 18:22
Hi @liaralabs , just tried with the flag that you mentioned above, and I've got still the same behavior.

Would a Fiddler trace help?

**Comment by liaralabs** [comment] 2020-08-16 18:30
Are you actually getting the basic auth dialog now, rather than the forms? If so, there's not much else that can be done from my end. Something is screwing with your request to login.

Some things you may consider trying:

- enable debug in the panel and attach to the log output and try logging in. See if the panel is throwing errors
- home network stuff at the router level. Have you made customizations that might affect every device connected to it?
- try an incognito session off your home network to rule out cookies and other such issues

Do you have problems authenticating with basic auth in any other applications?

Did you use special characters in your password? Some characters get lost and it's possible your password may not be set too what you think it is. If you have special characters try changing your password to something alphanumeric.

Unless the panel is spitting out errors directly, it's not likely server side.

**Comment by mcquiggd** [comment] 2020-09-02 16:25
For others experiencing this issue; using Edge Chromium, I found disabling Remote Torrent Adder extension, allowed me to log in to the panel.

Perhaps that might help others.

**Comment by couquino** [comment] 2020-10-09 09:15
> For others experiencing this issue; using Edge Chromium, I found disabling Remote Torrent Adder extension, allowed me to log in to the panel.
> 
> Perhaps that might help others.

+1 it works again for me when disabling Remote Torrent Adder

**Comment by flying-sausages** [comment] 2020-11-16 01:12
No response from OP for 3 months, closing issue

**Closed by flying-sausages** 2020-11-16 01:12 UTC

**Comment by jaum20** [comment] 2024-08-02 01:38
I have the same problem. I can login fine in sonarr, radarr, etc. But can't acces swizzin pannel
