### ISSUE TITLE
rclone web gui not configured

### ISSUE THREAD

**Issue by lukeholder** [swizzin/swizzin#592] opened 2021-02-13 05:19 UTC
## Bug description
rclone's web gui does not get configured or work.

## Reproduction steps
1. Install rclone
2. No rclone listed in sidebar linking to rclone web gui
3. confirm rclone is working fine from the command line

## Installed applications through swizzin
rclone

## Expected behavior
The rclone web gui should be accessible like all other services.

## Server Info
```
System:    Host: srv2326 Kernel: 4.19.0-14-amd64 x86_64 bits: 64 Console: tty 2 Distro: Debian GNU/Linux 10 (buster) 
Machine:   Type: Server System: Dell product: PowerEdge R220 v: 01 serial: <root required> 
           Mobo: Dell model: 081N4V v: A05 serial: <root required> UEFI [Legacy]: Dell v: 1.11.0 date: 09/10/2019 
CPU:       Topology: Quad Core model: Intel Xeon E3-1241 v3 bits: 64 type: MT MCP L2 cache: 8192 KiB 
           Speed: 3492 MHz min/max: 800/3900 MHz Core speeds (MHz): 1: 3492 2: 3498 3: 3492 4: 3493 5: 3492 6: 3492 7: 3492 
           8: 3495 
Graphics:  Device-1: Matrox Systems G200eR2 driver: mgag200 v: kernel 
           Display: tty server: N/A driver: mgag200 tty: 129x45 
           Message: Advanced graphics data unavailable in console. Try -G --display 
Audio:     Message: No Device data found. 
Network:   Device-1: Broadcom Limited NetXtreme BCM5720 Gigabit Ethernet PCIe driver: tg3 
           IF: eth0 state: up speed: 1000 Mbps duplex: full mac: 54:9f:35:25:64:ba 
           Device-2: Broadcom Limited NetXtreme BCM5720 Gigabit Ethernet PCIe driver: tg3 
           IF: eth1 state: down mac: 54:9f:35:25:64:bc 
Drives:    Local Storage: total: 7.28 TiB used: 454.96 GiB (6.1%) 
           ID-1: /dev/sda vendor: HGST (Hitachi) model: HDS724040ALE640 size: 3.64 TiB 
           ID-2: /dev/sdb vendor: HGST (Hitachi) model: HDN724040ALE640 size: 3.64 TiB 
RAID:      Device-1: md125 type: mdraid status: active raid: mirror report: 2/2 UU Components: online: sdb2~c1 sda3~c0 
           Device-2: md126 type: mdraid status: active raid: raid-0 report: N/A Components: online: sdb1~c1 sda2~c0 
           Device-3: md127 type: mdraid status: active raid: raid-0 report: N/A Components: online: sdb3~c1 sda4~c0 
Partition: ID-1: / size: 7.21 TiB used: 454.40 GiB (6.2%) fs: ext4 dev: /dev/md127 
           ID-2: /boot size: 464.6 MiB used: 47.0 MiB (10.1%) fs: ext4 dev: /dev/md125 
           ID-3: swap-1 size: 7.45 GiB used: 526.8 MiB (6.9%) fs: swap dev: /dev/md126 
Sensors:   System Temperatures: cpu: 26.0 C mobo: N/A 
           Fan Speeds (RPM): N/A 
Info:      Processes: 184 Uptime: 2d 6h 18m Memory: 15.50 GiB used: 2.91 GiB (18.8%) Init: systemd runlevel: 5 Shell: bash 
           inxi: 3.0.32 
```

## Is Swizzin up to date?
HEAD is now set to 96724b7

## Additional context

The rclone app installs and works fine from the cli.

rclone supports a web gui: https://rclone.org/gui/

But this is not configured with the swizzin user/password set to a htpasswd and the web gui is not accessible on the public web.

luke@myserver:~$ rclone rcd --rc-web-gui
2021/02/13 06:05:08 NOTICE: Web GUI exists. Update skipped.
2021/02/13 06:05:08 NOTICE: Serving Web GUI
2021/02/13 06:05:08 NOTICE: Serving remote control on http://localhost:5572/

The above command looks like it works but the remote control webpage is not publicly accessible.

**Comment by flying-sausages** [comment] 2021-02-13 12:00
Hey Luke, this is not a bug but a deliberate choice (an _anti_-feature?). Rclone is extremely bothersome to support, and we have made the conscious choice to merely provide the bare minimum for someone to achieve a working set up. The Web GUI has come up relatively "recently" compared to swizzin's history. Furthermore, anyone who is truly determined to enable it will surely figure out how.

With that said, I would welcome a PR to implement this Web-UI and enabling the acces to it from the dashboard from a contributor who is willing to also write the user documentation for this and support the questions in our Discord. I'd be happy to provide direct help with the implementation, but cannot commit my time to supporting rclone.

I'm going to close this and suggest that you check out the feathub and put a feature request there, as this issue is not exactly an actual bug but a feature request.

Hope explanation is satisfactory! Feel free to let me know here or in the Discord if you'd consider helping out the project and adding this.

**Closed by flying-sausages** 2021-02-13 12:00 UTC
