### ISSUE TITLE
[BUG] Screenshot plugin not working

### ISSUE THREAD

**Issue by rjroot** [swizzin/swizzin#927] opened 2022-11-23 02:54 UTC
### What happened?

Steps to reproduce:

1. Install package ffmpeg & screenshot plugin
2. Go to rutorrent webui
3. Error : Bad response from server: (200 [parsererror,getplugins]) TypeError: theWebUI.createSelectableLabelElement is not a function

Expected results: To load rutorrent webui properly, after installing screenshots, rutorrent webui shows the following.

![Screenshot_525](https://user-images.githubusercontent.com/40306337/203460790-36849ab3-82e2-47c5-805d-de353eb2154c.png)

### Swizzin commit

448031a

### What OS are you using?

Debian 11 (Bullseye) (brand new install), somehow rutorrent v3.10 (there is also a v4?)is getting installed despite on latest repo.

### What architecture is your OS?

amd64

**Comment by tonton63000** [comment] 2023-04-19 15:33
restart the script with your username and password and install ffmpeg.
It will solve the problem of screeshots

**Comment by stickz** [comment] 2023-04-19 19:11
This is an issue from last year. It's caused by caching issues with rutorrent. This has since been resolved in version 4.0.2 or higher. It can be closed off.

**Closed** 2023-07-16 22:33 UTC
Labels: bug
