### ISSUE TITLE
502 Bad Gateway in deluge 1.3 web ui[BUG] 

### ISSUE THREAD

**Issue by Dev-learn1** [swizzin/swizzin#932] opened 2022-11-30 19:28 UTC
### What happened?

hello
first thanksfor great script
installed deluge 2.3 and worked fine but downgraded to 1.3 and getting 502 bad gateway error so i thought on a clean install and seems found the problem and something is missing in installation files?

Steps to reproduce:

1. Install package 'box install deluge web'
2. Error 'bash: /usr/local/bin/swizzin/install/web.sh: No such file or directory'

### Swizzin commit

448031a

### What OS are you using?

Ubuntu 20.04 (Focal)

### What architecture is your OS?

arm64

### Relevant logs and output

```plaintext
box install deluge web
WARN    Package deluge already installed
INFO    Installing web
DOCS    Further reference:
        https://swizzin.ltd/applications/web
bash: /usr/local/bin/swizzin/install/web.sh: No such file or directory
```

**Comment by bakerboy448** [comment] 2022-11-30 19:29
Not a bug there is no app named `web` and box is space limited for variables exactly as the docs says

**Comment by matthieuki** [comment] 2022-12-18 16:04
I've got the same problem with deluge-web with deluge 1.3.15, but not with 2.3.
I've a clean install and when I go to https://MY_IP/deluge I get on a 502

### Log in /var/log/nginx/error.log

`2022/12/18 15:55:53 [error] 19613#19613: *2624 connect() failed (111: Unknown error) while connecting to upstream, client: 192.168.1.191, server: xxxxxx.xxxxxx.xxx, request: "GET /deluge/ HTTP/2.0", upstream: "http://127.0.0.1:10993/", host: "192.168.1.201"`

**Comment by hillbreaker** [comment] 2023-02-02 21:28
> Not a bug there is no app named `web` and box is space delimited for variables exactly as the docs says. This it correctly has no installer for `web`. Who/what/where said to install `web`

Don't know why OP is trying to install deluge "web" but i got a 502 too when trying to install deluge 1.3.15 via the installer. Deluge 2 is working.

**Comment by brettpetch** [comment] 2023-02-02 21:54
`box update` before trying again -- this should have been fixed in the most recent push.

**Comment by hillbreaker** [comment] 2023-02-02 23:25
Deluge 1.3.15 seems to be working now, thread can be marked as solved.

**Closed** 2023-02-02 23:27 UTC
Labels: bug
