### ISSUE TITLE
[BUG] Can´t login after fresh install!      python[254]: WARNING:core.htpasswd:Invalid login from master at x.x.x.x

### ISSUE THREAD

**Issue by littlAcen** [swizzin/swizzin#1021] opened 2023-05-27 16:05 UTC
### What happened?

Steps to reproduce:

1. Install swizzin
2. reboot
3. try to login

Expected results:
login

what do i do wrong?

### Swizzin commit

c943adc

### What OS are you using?

Debian 10 (Buster)

### What architecture is your OS?

amd64

### Relevant logs and output

```plaintext
May 27 16:00:13 vps-xxx-1 python[254]: WARNING:core.htpasswd:Invalid login from master at 128.xxx
May 27 16:00:55 vps-zap593113-1 python[254]: WARNING:core.htpasswd:Invalid login from master at 128xxx
May 27 16:02:07 vps-zap593113-1 python[254]: WARNING:core.htpasswd:Invalid login from master at 128.xxx
May 27 16:02:28 vps-zap593113-1 python[254]: WARNING:core.htpasswd:Invalid login from master at 128.xxx
May 27 16:02:40 vps-zap593113-1 python[254]: WARNING:core.htpasswd:Invalid login from master at 128.xxx
May 27 16:02:51 vps-zap593113-1 python[254]: WARNING:core.htpasswd:Invalid login from master at 128.xxx
```

**Comment by liaralabs** [comment] 2023-05-27 16:36
This is not a bug. The password you are providing is invalid. Did you perhaps use any special characters when choosing your password? (Dollar signs, spaces, etc) Bash scripts don't always handle this very well and a lot of our password grepping mechanisms may get hung up on special characters such as spaces when variables are being generated to set your password programmatically.

**Comment by flying-sausages** [comment] 2023-07-16 12:33
@littlAcen reset the master password and try again. let's close this within two weeks if there's no reply

**Closed** 2023-08-01 17:31 UTC
Labels: bug
