### ISSUE TITLE
[BUG] Service running but showing as disabled under service info panel

### ISSUE THREAD

**Issue by gyCfjSnO** [swizzin/swizzin#843] opened 2022-02-24 00:18 UTC
### What happened?

Webmin & Netdata are running but both showing as Disabled under the Service Info panel. Restart of device does not resolve issue.

<img width="359" alt="image" src="https://user-images.githubusercontent.com/49738152/155432734-375cde52-7af5-4d83-9f1a-c3d585756887.png">

### Swizzin commit

d5b8d97

### What OS are you using?

Debian 11 (Bullseye)

### What architecture is your OS?

amd64

### Relevant logs and output

[panel_log.txt](https://github.com/swizzin/swizzin/files/8167161/panel_log.txt)

**Comment by brettpetch** [comment] 2022-03-09 02:54
The service is likely running. Try killing it forcefully.

**Comment by gyCfjSnO** [comment] 2022-03-09 03:23
> The service is likely running. Try killing it forcefully.

That suggestion worked for Netdata, but not for Webmin.

**Comment by brettpetch** [comment] 2022-03-09 03:27
if you run `ps aux | grep webmin` are you seeing anything?

**Comment by gyCfjSnO** [comment] 2022-03-09 03:31
> 

```
htpc@HTPC:~$ ps aux | grep webmin
htpc       26598  0.0  0.0   6180   728 pts/0    S+   13:30   0:00 grep webmin
```

**Comment by bakerboy448** [comment] 2022-03-09 03:31
Duplicate of https://github.com/swizzin/swizzin_dashboard/issues/9

**Comment by sand-bit** [comment] 2022-09-14 14:10
It seems like on Ubuntu 22.04 with the commit as of [https://github.com/swizzin/swizzin/commit/027fe3f09733547ad22bf11a05f00f321d88d13d](https://github.com/swizzin/swizzin/commit/027fe3f09733547ad22bf11a05f00f321d88d13d) webmin shows as running, but in fact fails to load completely.

**Comment by liaralabs** [comment] 2022-10-16 01:42
Webmin fixed itself. The issue was that it took them years to update from a sysv init script to a systemd service.

> webmin fails to load completely is a different bug

I cannot see any issues with netdata. There is a systemd service for this one as well, the service may be disabled in your case?

![image](https://user-images.githubusercontent.com/30909703/196013906-75236811-fdf7-4435-9315-190b639625af.png)
![image](https://user-images.githubusercontent.com/30909703/196013914-710ea649-6191-481c-8b13-306099d68d41.png)

**Closed by liaralabs** 2022-10-16 01:42 UTC
Labels: bug
