### ISSUE TITLE
[BUG] Bazarr 502 Bad Gateway fresh install on Ubuntu 20.04

### ISSUE THREAD

**Issue by Eisteed** [swizzin/swizzin#737] opened 2021-08-16 14:53 UTC
### What happened?

Steps to reproduce:

Fresh install of Ubuntu 20.04.2.0 LTS
1. Install package 'bazarr, deluge, deluge web, filebrowser, jackett, lidarr, radarr, sonarr'
2. Go to bazarr web panel
3. Error 502 Bad Gateway nginx

Expected results:
working web panel of bazarr.

### Swizzin commit

1f1ac91

### What OS are you using?

Ubuntu 20.04

### What architecture is your OS?

amd64

### Relevant logs and output
nginx error log
`*49 connect() failed (111:connection refused) while connecting to upstream (http://127.0.0.1:6767/bazarr)`

systemctl status bazarr 
`:  ERROR (app:1890) - Exception on /bazarr/ [GET]`

**Comment by Eisteed** [comment] 2021-08-16 15:04
Tried uninstalling / reinstalling bazarr and I also get those error when installing :

`...	Cloning into '/opt/bazarr'
chown: Cannot access 'bazarr': No such file or directory
	✔   cloned
/usr/local/bin/swizzin/install/bazarr.sh: line 35 : cd: bazarr: No such file or directory
...	Checking python depends
	✔   Dependencies installed`

Errors translation are no file or folder of this type

**Comment by flying-sausages** [comment] 2021-08-16 15:44
Dupe of #722

**Closed by flying-sausages** 2021-08-16 15:45 UTC
Labels: bug
