### ISSUE TITLE
Subsonic - 503 Error

### ISSUE THREAD

**Issue by Viper911** [swizzin/swizzin#454] opened 2020-11-15 14:18 UTC
##  Bug description
Fresh install of apps doesn't work

## Reproduction steps
Do a fresh install on a fresh OS

## Expected behavior
Should work

## Server Info
Ubuntu 20.04)
Vanilla download

## Is Swizzin up to date?
Yes

## Additional context
Running this ahead of Swizzin install seems to fix it
sudo add-apt-repository ppa:linuxuprising/java
sudo apt update
sudo apt install oracle-java15-installer
sudo apt install python3-pip

With this after Install
sudo update-alternatives --config java   ----  set to v8

^[[2m[Sun Nov 15 13:27:39]^[(B^[[m ^[[2m...     Downloading and installing subsonic^[(B^[[m
Selecting previously unselected package subsonic.
(Reading database ... 111096 files and directories currently installed.)
Preparing to unpack subsonic.deb ...
Unpacking subsonic (6.1.6) ...
Setting up subsonic (6.1.6) ...
Processing triggers for systemd (245.4-4ubuntu3.3) ...
^[[2m[Sun Nov 15 13:27:53]^[(B^[[m      ^[[32m^[[2m✔   ^[[3mSubsonic installed^[(B^[[m
^[[2m[Sun Nov 15 13:27:53]^[(B^[[m ^[[2m...     Modifying Subsonic startup script^[(B^[[m
^[[2m[Sun Nov 15 13:27:53]^[(B^[[m      ^[[32m^[[2m✔   ^[[3mDone^[(B^[[m
^[[2m[Sun Nov 15 13:27:53]^[(B^[[m ^[[2m...     Enabling Subsonic Systemd configuration^[(B^[[m
sh: 0: getcwd() failed: No such file or directory
^[[2m[Sun Nov 15 13:27:55]^[(B^[[m      ^[[32m^[[2m✔   ^[[3mStarted subsonic^[(B^[[m
^[[2m[Sun Nov 15 13:27:55]^[(B^[[m ^[[2m...     Configuring nginx^[(B^[[m
^[[2m[Sun Nov 15 13:27:55]^[(B^[[m      ^[[32m^[[2m✔   ^[[3mDone^[(B^[[m
^[[2m[Sun Nov 15 13:27:55]^[(B^[[m ^[[32m^[[1mSUCCESS   Subsonic installed^[(B^[[m
e949cc71-2d3f-4cf2-ae78-ac0e0debb9d2
^[[2m[Sun Nov 15 13:27:55]^[(B^[[m ^[[36mLOG    Inserted apt logcheck marker^[(B^[[m
^[[2m[Sun Nov 15 13:27:55]^[(B^[[m ^[[36mLOG    Variables unset^[(B^[[m
^[[2m[Sun Nov 15 13:27:55]^[(B^[[m ^[[36mLOG    New variables exported^[(B^[[m
^[[2m[Sun Nov 15 13:27:55]^[(B^[[m ^[[36mLOG    No dpkg locks found^[(B^[[m
Reading package lists...
Building dependency tree...
Reading state information...
^[[2m[Sun Nov 15 13:27:55]^[(B^[[m ^[[36mLOG    Apt check returned succesfully^[(B^[[m
^[[2m[Sun Nov 15 13:27:55]^[(B^[[m ^[[36mLOG    Apt log age = 0, update is forced= ^[(B^[[m
^[[2m[Sun Nov 15 13:27:55]^[(B^[[m ^[[36mLOG     Apt sufficiently up to date, skipping^[(B^[[m
Reading package lists...
Building dependency tree...

**Comment by liaralabs** [comment] 2020-11-15 20:50
I cannot reproduce this issue and do not need the workarounds you've suggested.

It would be helpful if you can include logs from your install as the terminal output during installs tend not to contain any helpful information. All the helpful info is sent to the logs.

Please make sure you've read the troubleshooting guides if you need basic assistance debugging an application or providing logs: https://swizzin.ltd/guides/troubleshooting/

**Comment by flying-sausages** [comment] 2020-11-16 14:54
I've encountered some weirdness around the use of `cd` within the script.

Whether or not it's broken, there is now a PR for Airsonic, and I'm assuming you'll take the maintained and free version of Subsonic as a fix.

**Comment by Viper911** [comment] 2020-11-16 15:07
Yea, if your getting rid of subsonic, probably not worth the fix, whatever it may be.  Like I say I have it working I just had to install Oracle java 15 and pip3 manually before installing swizzin.  I really am using it more for audiobooks.  Would be great to see something like BookSonic added as well (or whatever latest software is out there that is focused on books).  Same could be said for Readarr (or LazyLibrarian).  In any case you can close this issue, it was more of an FYI on what I did to fix it, if you wanted to include it in the short term.

**Comment by flying-sausages** [comment] 2020-11-16 15:13
If you'd like to request some software, please use the feathub link in the README.md

**Comment by Viper911** [comment] 2020-11-16 15:31
Understood, was just making the comment that subsonic is not necessarily needed if you don't want to update it as I have it working and am likely going to use a different app anyways.

**Comment by flying-sausages** [comment] 2021-05-10 09:04
Closed as Subsonic has been deprecated

**Closed by flying-sausages** 2021-05-10 09:04 UTC
Labels: Not following issue template
